#!/bin/bash
################################################################################
# Generate EE Definitions for All Organizations
################################################################################
# This script queries AWX for all organizations and generates an EE definitions
# file that includes EEs for each organization
################################################################################

set -e

# Configuration
AWX_API_ENDPOINT="${AWX_API_ENDPOINT:-http://localhost:30080}"
AWX_API_USER="${AWX_API_USER:-admin}"
AWX_API_PASSWORD="${AWX_API_PASSWORD}"
OUTPUT_FILE="${1:-ee-definitions-all-orgs.yaml}"

# Color codes
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
RESET='\033[0m'

echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"
echo -e "${BLUE}  Generate EE Definitions for All Organizations${RESET}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${RESET}"

# Check for required tools
if ! command -v curl &> /dev/null; then
    echo -e "${RED}✗${RESET} curl is required but not installed"
    exit 1
fi

if ! command -v jq &> /dev/null; then
    echo -e "${YELLOW}⚠${RESET} jq is recommended for better output formatting"
fi

# Get organizations from AWX API
echo -e "${BLUE}→${RESET} Fetching organizations from AWX API..."

ORGS_RESPONSE=$(curl -s -u "${AWX_API_USER}:${AWX_API_PASSWORD}" \
    "${AWX_API_ENDPOINT}/api/v2/organizations/")

if [[ $? -ne 0 ]]; then
    echo -e "${RED}✗${RESET} Failed to connect to AWX API"
    exit 1
fi

# Parse organizations
if command -v jq &> /dev/null; then
    ORG_COUNT=$(echo "$ORGS_RESPONSE" | jq -r '.count')
    echo -e "${GREEN}✓${RESET} Found ${ORG_COUNT} organization(s)"
    
    # Generate YAML file
    echo -e "${BLUE}→${RESET} Generating ${OUTPUT_FILE}..."
    
    cat > "${OUTPUT_FILE}" <<'EOF'
---
# AWX Execution Environment Definitions for All Organizations
# Auto-generated by generate_ee_for_all_orgs.sh
# Usage: source awx.conf && sudo -E ./manage_awx_ee.sh --build-all --definitions THIS_FILE

defaults:
  container_runtime: podman
  load_to_k3s: true
  register_in_awx: true

execution_environments:
EOF

    # Define the base EE types
    declare -a EE_TYPES=(
        "minimal:examples/ee-minimal.yml:awx-ee-minimal:latest:Minimal execution environment with ansible-core"
        "collections:examples/ee-collections.yml:awx-ee-collections:latest:EE with common Ansible collections"
        "network:examples/ee-python-deps.yml:awx-ee-network:latest:EE with network automation libraries"
    )
    
    # For each organization, create EE entries
    echo "$ORGS_RESPONSE" | jq -r '.results[] | "\(.id)|\(.name)"' | while IFS='|' read -r ORG_ID ORG_NAME; do
        echo -e "${BLUE}→${RESET} Adding EEs for organization: ${ORG_NAME} (ID: ${ORG_ID})"
        
        for EE_DEF in "${EE_TYPES[@]}"; do
            IFS=':' read -r EE_TYPE EE_FILE IMAGE_TAG IMAGE_VERSION DESCRIPTION <<< "$EE_DEF"
            
            cat >> "${OUTPUT_FILE}" <<EOF
  - name: "AWX EE ${EE_TYPE^} - ${ORG_NAME}"
    description: "${DESCRIPTION} for ${ORG_NAME}"
    ee_file: "${EE_FILE}"
    image_tag: "${IMAGE_TAG}"
    organization: ${ORG_ID}
    enabled: true
  
EOF
        done
    done
    
    echo -e "${GREEN}✓${RESET} Generated ${OUTPUT_FILE}"
    echo ""
    echo -e "${BLUE}ℹ${RESET} To build and register all EEs, run:"
    echo -e "   ${GREEN}source awx.conf && sudo -E ./manage_awx_ee.sh --build-all --definitions ${OUTPUT_FILE}${RESET}"
    echo ""
    echo -e "${YELLOW}⚠${RESET} Note: Images are built once and reused across organizations"
    echo -e "${YELLOW}⚠${RESET} Only the registration is done separately for each organization"
    
else
    # Fallback without jq
    echo -e "${YELLOW}⚠${RESET} Install jq for automatic generation"
    echo -e "${BLUE}ℹ${RESET} Manual organization IDs found:"
    echo "$ORGS_RESPONSE" | grep -oP '"id":\K[0-9]+' | while read -r ORG_ID; do
        echo "  - Organization ID: ${ORG_ID}"
    done
fi
