#!/bin/bash

################################################################################
# AWX Tower Installation Script for Ubuntu 24.04
################################################################################
# Description: Automated installation of AWX (Open Source Ansible Tower)
#              using K3s and AWX Operator on Ubuntu 24.04 LTS
# Version: 1.0.0
# Date: February 18, 2026
# Requirements: Ubuntu 24.04 LTS, 4+ CPU cores, 8+ GB RAM, 40+ GB disk
################################################################################

set -e  # Exit on error
set -o pipefail  # Exit on pipe failure

################################################################################
# Configuration Variables
################################################################################

AWX_VERSION="${AWX_VERSION:-2.19.1}"  # AWX Operator version
AWX_NAMESPACE="${AWX_NAMESPACE:-awx}"
AWX_INSTANCE_NAME="${AWX_INSTANCE_NAME:-awx}"
ADMIN_USER="${ADMIN_USER:-admin}"
ADMIN_PASSWORD="${ADMIN_PASSWORD:-}"  # Auto-generate if empty
K3S_VERSION="${K3S_VERSION:-}"  # Latest stable if empty
LOG_FILE="/var/log/awx-install.log"
SKIP_K3S=false
UNINSTALL_MODE=false

################################################################################
# Color Codes for Output
################################################################################

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
MAGENTA='\033[0;35m'
NC='\033[0m'  # No Color

################################################################################
# Output Functions
################################################################################

log() {
    echo "$(date '+%Y-%m-%d %H:%M:%S') - $*" >> "$LOG_FILE"
}

print_header() {
    echo -e "\n${CYAN}========================================${NC}"
    echo -e "${CYAN}$1${NC}"
    echo -e "${CYAN}========================================${NC}\n"
    log "HEADER: $1"
}

print_success() {
    echo -e "${GREEN}✓ $1${NC}"
    log "SUCCESS: $1"
}

print_error() {
    echo -e "${RED}✗ Error: $1${NC}" >&2
    log "ERROR: $1"
}

print_warning() {
    echo -e "${YELLOW}⚠ Warning: $1${NC}"
    log "WARNING: $1"
}

print_info() {
    echo -e "${BLUE}ℹ $1${NC}"
    log "INFO: $1"
}

print_step() {
    echo -e "${MAGENTA}➜ $1${NC}"
    log "STEP: $1"
}

################################################################################
# Usage Information
################################################################################

usage() {
    cat <<EOF
${CYAN}AWX Tower Installation Script for Ubuntu 24.04${NC}

Usage: $0 [OPTIONS]

Options:
    -h, --help              Display this help message
    --awx-version VERSION   Specify AWX Operator version (default: ${AWX_VERSION})
    --admin-password PASS   Set custom admin password (auto-generated by default)
    --namespace NAME        Custom namespace (default: ${AWX_NAMESPACE})
    --skip-k3s              Skip K3s installation if already present
    --uninstall             Remove AWX and K3s installation
    -v, --verbose           Enable verbose output

Examples:
    # Standard installation
    sudo $0

    # Custom configuration
    sudo $0 --awx-version 2.19.1 --namespace production

    # Skip K3s if already installed
    sudo $0 --skip-k3s

    # Uninstall AWX
    sudo $0 --uninstall

Requirements:
    - Ubuntu 24.04 LTS (64-bit)
    - Root or sudo privileges
    - 4+ CPU cores, 8+ GB RAM, 40+ GB disk space
    - Internet connectivity

EOF
    exit 0
}

################################################################################
# Cleanup Function
################################################################################

cleanup_on_error() {
    print_error "Installation failed. Check logs at $LOG_FILE"
    print_info "To retry, fix the issue and run the script again"
    print_info "To clean up, run: $0 --uninstall"
    exit 1
}

trap cleanup_on_error ERR

################################################################################
# Prerequisites Validation
################################################################################

check_prerequisites() {
    print_header "Checking Prerequisites"

    # Check if running as root
    if [[ $EUID -ne 0 ]]; then
        print_error "This script must be run as root or with sudo"
        exit 1
    fi
    print_success "Running as root"

    # Check Ubuntu version
    if [[ ! -f /etc/os-release ]]; then
        print_error "Cannot detect OS version"
        exit 1
    fi

    source /etc/os-release
    if [[ "$ID" != "ubuntu" ]]; then
        print_error "This script is designed for Ubuntu. Detected: $ID"
        exit 1
    fi

    if [[ "$VERSION_ID" != "24.04" ]]; then
        print_warning "This script is tested on Ubuntu 24.04. You have $VERSION_ID"
        print_info "Continuing anyway..."
    fi
    print_success "Ubuntu version: $VERSION_ID"

    # Check CPU cores
    CPU_CORES=$(nproc)
    if [[ $CPU_CORES -lt 2 ]]; then
        print_error "Minimum 2 CPU cores required. Found: $CPU_CORES"
        exit 1
    fi
    print_success "CPU cores: $CPU_CORES"

    # Check memory
    TOTAL_MEM_GB=$(free -g | awk '/^Mem:/{print $2}')
    if [[ $TOTAL_MEM_GB -lt 4 ]]; then
        print_error "Minimum 4 GB RAM required. Found: ${TOTAL_MEM_GB} GB"
        exit 1
    fi
    print_success "Memory: ${TOTAL_MEM_GB} GB"

    # Check disk space
    DISK_SPACE_GB=$(df -BG / | awk 'NR==2 {print $4}' | sed 's/G//')
    if [[ $DISK_SPACE_GB -lt 20 ]]; then
        print_error "Minimum 20 GB free disk space required. Found: ${DISK_SPACE_GB} GB"
        exit 1
    fi
    print_success "Free disk space: ${DISK_SPACE_GB} GB"

    # Check internet connectivity
    if ! ping -c 1 -W 5 8.8.8.8 &> /dev/null; then
        print_error "No internet connectivity detected"
        exit 1
    fi
    print_success "Internet connectivity verified"

    print_success "All prerequisites met"
}

################################################################################
# System Preparation
################################################################################

prepare_system() {
    print_header "Preparing System"

    print_step "Updating package lists..."
    apt-get update -qq
    print_success "Package lists updated"

    print_step "Installing required packages..."
    apt-get install -y -qq \
        curl \
        wget \
        git \
        gnupg \
        software-properties-common \
        ca-certificates \
        apt-transport-https \
        python3 \
        python3-pip \
        jq \
        > /dev/null 2>&1
    print_success "Required packages installed"

    # Disable swap (Kubernetes requirement)
    if [[ $(swapon --show | wc -l) -gt 0 ]]; then
        print_step "Disabling swap (Kubernetes requirement)..."
        swapoff -a
        sed -i '/swap/d' /etc/fstab
        print_success "Swap disabled"
    else
        print_info "Swap already disabled"
    fi

    # Configure firewall
    print_step "Configuring firewall..."
    if command -v ufw &> /dev/null; then
        ufw --force enable
        ufw allow 22/tcp comment 'SSH' > /dev/null
        ufw allow 80/tcp comment 'HTTP' > /dev/null
        ufw allow 443/tcp comment 'HTTPS' > /dev/null
        ufw allow 6443/tcp comment 'Kubernetes API' > /dev/null
        ufw allow ${NODEPORT:-30080}/tcp comment 'AWX NodePort' > /dev/null
        print_success "Firewall configured (opened ports: 22, 80, 443, 6443, ${NODEPORT:-30080})"
    else
        print_warning "UFW not found, skipping firewall configuration"
    fi

    print_success "System preparation completed"
}

################################################################################
# K3s Installation
################################################################################

install_k3s() {
    print_header "Installing K3s (Lightweight Kubernetes)"

    if $SKIP_K3S; then
        if command -v k3s &> /dev/null; then
            print_info "K3s installation skipped (--skip-k3s flag)"
            return 0
        else
            print_error "K3s not found but --skip-k3s was specified"
            exit 1
        fi
    fi

    if command -v k3s &> /dev/null; then
        print_warning "K3s already installed"
        K3S_EXISTING_VERSION=$(k3s --version | head -n 1)
        print_info "Existing version: $K3S_EXISTING_VERSION"
        print_info "Continuing with existing installation..."
        return 0
    fi

    print_step "Downloading and installing K3s..."
    if [[ -n "$K3S_VERSION" ]]; then
        curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION="$K3S_VERSION" sh -s - \
            --write-kubeconfig-mode 644 \
            --disable traefik
    else
        curl -sfL https://get.k3s.io | sh -s - \
            --write-kubeconfig-mode 644 \
            --disable traefik
    fi
    print_success "K3s installed"

    # Configure kubectl
    print_step "Configuring kubectl..."
    export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
    echo "export KUBECONFIG=/etc/rancher/k3s/k3s.yaml" >> /root/.bashrc
    
    # Create symlink for easier kubectl access
    if [[ ! -f /usr/local/bin/kubectl ]]; then
        ln -s /usr/local/bin/k3s /usr/local/bin/kubectl
    fi
    print_success "kubectl configured"

    # Wait for K3s to be ready
    print_step "Waiting for K3s cluster to be ready..."
    for i in {1..30}; do
        if kubectl cluster-info &> /dev/null; then
            print_success "K3s cluster is ready"
            break
        fi
        if [[ $i -eq 30 ]]; then
            print_error "K3s cluster failed to start"
            exit 1
        fi
        sleep 2
    done

    # Verify cluster health
    kubectl get nodes
    print_success "K3s installation completed"
}

################################################################################
# AWX Operator Deployment
################################################################################

deploy_awx_operator() {
    print_header "Deploying AWX Operator"

    export KUBECONFIG=/etc/rancher/k3s/k3s.yaml

    # Create namespace
    print_step "Creating AWX namespace..."
    if kubectl get namespace "$AWX_NAMESPACE" &> /dev/null; then
        print_warning "Namespace $AWX_NAMESPACE already exists"
    else
        kubectl create namespace "$AWX_NAMESPACE"
        print_success "Namespace $AWX_NAMESPACE created"
    fi

    # Deploy AWX Operator using Kustomize
    print_step "Deploying AWX Operator version $AWX_VERSION..."
    
    OPERATOR_URL="https://raw.githubusercontent.com/ansible/awx-operator/${AWX_VERSION}/deploy/awx-operator.yaml"
    
    # Try to download and apply operator manifest
    if curl -sfL "$OPERATOR_URL" -o /tmp/awx-operator.yaml; then
        kubectl apply -f /tmp/awx-operator.yaml -n "$AWX_NAMESPACE"
        print_success "AWX Operator deployed"
    else
        print_warning "Failed to download operator from URL, using Kustomize method..."
        
        # Alternative: Use kustomize from GitHub
        kubectl apply -k "https://github.com/ansible/awx-operator/config/default?ref=${AWX_VERSION}" -n "$AWX_NAMESPACE"
        print_success "AWX Operator deployed via Kustomize"
    fi

    # Wait for operator to be ready
    print_step "Waiting for AWX Operator to be ready..."
    kubectl wait --for=condition=ready pod \
        -l control-plane=controller-manager \
        -n "$AWX_NAMESPACE" \
        --timeout=300s
    print_success "AWX Operator is ready"

    # Show operator status
    kubectl get pods -n "$AWX_NAMESPACE"
}

################################################################################
# AWX Instance Creation
################################################################################

create_awx_instance() {
    print_header "Creating AWX Instance"

    export KUBECONFIG=/etc/rancher/k3s/k3s.yaml

    # Generate admin password if not provided
    if [[ -z "$ADMIN_PASSWORD" ]]; then
        ADMIN_PASSWORD=$(openssl rand -base64 20 | tr -dc A-Za-z0-9)
        print_info "Generated admin password: $ADMIN_PASSWORD"
    fi

    # Create AWX instance manifest
    print_step "Creating AWX instance configuration..."
    
    # Info about projects persistence
    if [[ "${PROJECTS_PERSISTENCE:-false}" == "false" ]]; then
        print_info "Projects persistence disabled (K3s local-path doesn't support ReadWriteMany)"
        print_info "Projects will use ephemeral storage. For persistent projects, use NFS storage."
    else
        print_warning "Projects persistence enabled - ensure your storage class supports ReadWriteMany (RWX)"
    fi
    
    cat > /tmp/awx-instance.yaml <<EOF
---
apiVersion: v1
kind: Secret
metadata:
  name: ${AWX_INSTANCE_NAME}-admin-password
  namespace: ${AWX_NAMESPACE}
stringData:
  password: ${ADMIN_PASSWORD}
type: Opaque
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: ${AWX_INSTANCE_NAME}
  namespace: ${AWX_NAMESPACE}
spec:
  service_type: ${SERVICE_TYPE:-NodePort}
  nodeport_port: ${NODEPORT:-30080}
  
  admin_user: ${ADMIN_USER}
  admin_password_secret: ${AWX_INSTANCE_NAME}-admin-password

  postgres_storage_class: local-path
  postgres_storage_requirements:
    requests:
      storage: ${POSTGRES_STORAGE_SIZE:-8Gi}

  # Projects persistence disabled by default for K3s local-path compatibility
  # K3s local-path only supports ReadWriteOnce (RWO), but AWX projects require ReadWriteMany (RWX)
  # To enable: Use NFS storage or set PROJECTS_PERSISTENCE=true with RWX-capable storage class
  projects_persistence: ${PROJECTS_PERSISTENCE:-false}
EOF

    # Add projects storage configuration only if persistence is enabled
    if [[ "${PROJECTS_PERSISTENCE:-false}" == "true" ]]; then
        cat >> /tmp/awx-instance.yaml <<EOF
  projects_storage_class: ${PROJECTS_STORAGE_CLASS:-local-path}
  projects_storage_size: ${PROJECTS_STORAGE_SIZE:-8Gi}
EOF
    fi

    # Add resource requirements
    cat >> /tmp/awx-instance.yaml <<EOF

  web_resource_requirements:
    requests:
      cpu: 500m
      memory: 2Gi
    limits:
      cpu: 1000m
      memory: 4Gi

  task_resource_requirements:
    requests:
      cpu: 500m
      memory: 2Gi
    limits:
      cpu: 1000m
      memory: 4Gi

  ee_resource_requirements:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1000m
      memory: 2Gi
EOF

    print_success "AWX instance configuration created"

    # Apply AWX instance
    print_step "Deploying AWX instance (this may take 5-15 minutes)..."
    kubectl apply -f /tmp/awx-instance.yaml
    print_success "AWX instance manifest applied"

    # Monitor deployment
    print_info "Monitoring deployment progress..."
    print_info "You can watch progress in another terminal with:"
    print_info "  kubectl logs -f deployment/awx-operator-controller-manager -n $AWX_NAMESPACE"
}

################################################################################
# Deployment Monitoring
################################################################################

wait_for_awx_deployment() {
    print_header "Waiting for AWX Deployment"

    export KUBECONFIG=/etc/rancher/k3s/k3s.yaml

    print_info "This may take 10-15 minutes. Please be patient..."

    # Wait for AWX deployment to be created
    print_step "Waiting for AWX resources to be created..."
    for i in {1..60}; do
        if kubectl get deployment "${AWX_INSTANCE_NAME}-web" -n "$AWX_NAMESPACE" &> /dev/null; then
            print_success "AWX deployment created"
            break
        fi
        if [[ $i -eq 60 ]]; then
            print_error "Timeout waiting for AWX deployment"
            kubectl get all -n "$AWX_NAMESPACE"
            exit 1
        fi
        sleep 5
    done

    # Wait for all pods to be ready
    print_step "Waiting for AWX pods to be ready..."
    
    # Wait for PostgreSQL pods to be created first
    print_info "Waiting for PostgreSQL pods to be created..."
    for i in {1..60}; do
        if kubectl get pod -l app.kubernetes.io/component=postgres -n "$AWX_NAMESPACE" 2>/dev/null | grep -q postgres; then
            print_info "PostgreSQL pods created"
            break
        fi
        if [[ $i -eq 60 ]]; then
            print_warning "PostgreSQL pods not found, checking operator status..."
            kubectl logs deployment/awx-operator-controller-manager -n "$AWX_NAMESPACE" --tail=30
        fi
        sleep 5
    done
    
    # Wait for postgres to be ready
    if kubectl get pod -l app.kubernetes.io/component=postgres -n "$AWX_NAMESPACE" &> /dev/null; then
        kubectl wait --for=condition=ready pod \
            -l app.kubernetes.io/component=postgres \
            -n "$AWX_NAMESPACE" \
            --timeout=600s
        print_success "PostgreSQL ready"
    fi

    # Wait for web deployment
    kubectl wait --for=condition=available deployment \
        "${AWX_INSTANCE_NAME}-web" \
        -n "$AWX_NAMESPACE" \
        --timeout=600s
    print_success "AWX web service ready"

    # Wait for task deployment
    kubectl wait --for=condition=available deployment \
        "${AWX_INSTANCE_NAME}-task" \
        -n "$AWX_NAMESPACE" \
        --timeout=600s
    print_success "AWX task service ready"

    # Wait for AWX service to be created
    print_step "Waiting for AWX service to be created..."
    for i in {1..60}; do
        if kubectl get svc "${AWX_INSTANCE_NAME}-service" -n "$AWX_NAMESPACE" &> /dev/null; then
            print_success "AWX service created"
            break
        fi
        if [[ $i -eq 60 ]]; then
            print_error "Timeout: AWX service not created after 5 minutes"
            print_info "Checking AWX operator logs..."
            kubectl logs deployment/awx-operator-controller-manager -n "$AWX_NAMESPACE" --tail=50
            print_info "Checking AWX custom resource status..."
            kubectl describe awx "$AWX_INSTANCE_NAME" -n "$AWX_NAMESPACE"
            print_error "Installation failed. Check logs above for details."
            exit 1
        fi
        sleep 5
    done

    print_success "AWX deployment completed successfully!"

    # Show all pods
    echo ""
    kubectl get pods -n "$AWX_NAMESPACE"
}

################################################################################
# Access Information
################################################################################

display_access_info() {
    print_header "AWX Access Information"

    export KUBECONFIG=/etc/rancher/k3s/k3s.yaml

    # Verify AWX service exists
    if ! kubectl get svc "${AWX_INSTANCE_NAME}-service" -n "$AWX_NAMESPACE" &> /dev/null; then
        print_error "AWX service '${AWX_INSTANCE_NAME}-service' not found in namespace '${AWX_NAMESPACE}'!"
        print_info "Available services:"
        kubectl get svc -n "$AWX_NAMESPACE"
        print_info "Check AWX resource status with:"
        echo "  kubectl describe awx ${AWX_INSTANCE_NAME} -n ${AWX_NAMESPACE}"
        echo "  kubectl logs deployment/awx-operator-controller-manager -n ${AWX_NAMESPACE}"
        exit 1
    fi

    # Get NodePort
    NODE_PORT=$(kubectl get svc "${AWX_INSTANCE_NAME}-service" -n "$AWX_NAMESPACE" -o jsonpath='{.spec.ports[0].nodePort}')
    
    # Get node IP
    NODE_IP=$(hostname -I | awk '{print $1}')

    # Retrieve admin password from secret
    STORED_PASSWORD=$(kubectl get secret "${AWX_INSTANCE_NAME}-admin-password" \
        -n "$AWX_NAMESPACE" \
        -o jsonpath='{.data.password}' | base64 -d)

    # Save credentials to file
    CREDS_FILE="/root/awx-credentials.txt"
    cat > "$CREDS_FILE" <<EOF
AWX Tower Access Information
========================================
Generated: $(date)

Web Interface URL:
  http://${NODE_IP}:${NODE_PORT}
  http://localhost:${NODE_PORT} (if accessing locally)

Login Credentials:
  Username: ${ADMIN_USER}
  Password: ${STORED_PASSWORD}

Namespace: ${AWX_NAMESPACE}
Instance Name: ${AWX_INSTANCE_NAME}

Useful Commands:
  # View AWX pods
  kubectl get pods -n ${AWX_NAMESPACE}

  # View AWX logs
  kubectl logs deployment/${AWX_INSTANCE_NAME}-web -n ${AWX_NAMESPACE}
  kubectl logs deployment/${AWX_INSTANCE_NAME}-task -n ${AWX_NAMESPACE}

  # Get service info
  kubectl get svc -n ${AWX_NAMESPACE}

  # Access AWX shell
  kubectl exec -it deployment/${AWX_INSTANCE_NAME}-task -n ${AWX_NAMESPACE} -- bash

========================================
EOF

    chmod 600 "$CREDS_FILE"

    # Display access information
    echo -e "\n${GREEN}╔════════════════════════════════════════════════════════════╗${NC}"
    echo -e "${GREEN}║          AWX Tower Successfully Installed!                 ║${NC}"
    echo -e "${GREEN}╚════════════════════════════════════════════════════════════╝${NC}\n"

    echo -e "${CYAN}Web Interface:${NC}"
    echo -e "  ${YELLOW}http://${NODE_IP}:${NODE_PORT}${NC}"
    echo -e "  ${YELLOW}http://localhost:${NODE_PORT}${NC} ${BLUE}(if accessing locally)${NC}\n"

    echo -e "${CYAN}Login Credentials:${NC}"
    echo -e "  Username: ${YELLOW}${ADMIN_USER}${NC}"
    echo -e "  Password: ${YELLOW}${STORED_PASSWORD}${NC}\n"

    echo -e "${CYAN}Credentials saved to:${NC} ${YELLOW}${CREDS_FILE}${NC}\n"

    print_info "Access the AWX web interface and complete initial setup:"
    echo -e "  ${BLUE}1.${NC} Create an Organization"
    echo -e "  ${BLUE}2.${NC} Add Credentials (SSH keys, cloud credentials)"
    echo -e "  ${BLUE}3.${NC} Create Inventories"
    echo -e "  ${BLUE}4.${NC} Add Projects (Git repositories with playbooks)"
    echo -e "  ${BLUE}5.${NC} Create Job Templates"
    echo -e "  ${BLUE}6.${NC} Run your first playbook!\n"

    print_info "Documentation: https://ansible.readthedocs.io/projects/awx/"
}

################################################################################
# Uninstall Function
################################################################################

uninstall_awx() {
    print_header "Uninstalling AWX"

    export KUBECONFIG=/etc/rancher/k3s/k3s.yaml

    print_warning "This will remove AWX and K3s from your system"
    read -p "Are you sure you want to continue? (yes/no): " -r
    if [[ ! $REPLY =~ ^[Yy][Ee][Ss]$ ]]; then
        print_info "Uninstall cancelled"
        exit 0
    fi

    # Delete AWX instance
    if kubectl get namespace "$AWX_NAMESPACE" &> /dev/null; then
        print_step "Removing AWX instance..."
        kubectl delete awx "$AWX_INSTANCE_NAME" -n "$AWX_NAMESPACE" --timeout=120s || true
        print_success "AWX instance removed"

        print_step "Removing AWX namespace..."
        kubectl delete namespace "$AWX_NAMESPACE" --timeout=120s || true
        print_success "AWX namespace removed"
    else
        print_info "AWX namespace not found, skipping..."
    fi

    # Uninstall K3s
    if command -v k3s-uninstall.sh &> /dev/null; then
        print_step "Uninstalling K3s..."
        k3s-uninstall.sh
        print_success "K3s uninstalled"
    else
        print_info "K3s not found, skipping..."
    fi

    # Clean up files
    print_step "Cleaning up files..."
    rm -f /root/awx-credentials.txt
    rm -f /tmp/awx-*.yaml
    print_success "Cleanup completed"

    print_success "AWX has been completely uninstalled"
}

################################################################################
# Main Function
################################################################################

main() {
    # Parse command line arguments
    while [[ $# -gt 0 ]]; do
        case $1 in
            -h|--help)
                usage
                ;;
            --awx-version)
                AWX_VERSION="$2"
                shift 2
                ;;
            --admin-password)
                ADMIN_PASSWORD="$2"
                shift 2
                ;;
            --namespace)
                AWX_NAMESPACE="$2"
                shift 2
                ;;
            --skip-k3s)
                SKIP_K3S=true
                shift
                ;;
            --uninstall)
                UNINSTALL_MODE=true
                shift
                ;;
            -v|--verbose)
                set -x
                shift
                ;;
            *)
                print_error "Unknown option: $1"
                usage
                ;;
        esac
    done

    # Initialize log file
    touch "$LOG_FILE"
    chmod 600 "$LOG_FILE"

    # Display banner
    echo -e "${CYAN}"
    cat <<'EOF'
    ╔═══════════════════════════════════════════════════════╗
    ║                                                       ║
    ║        AWX Tower Installation Script                 ║
    ║        for Ubuntu 24.04 LTS                          ║
    ║                                                       ║
    ║        Open Source Ansible Automation                ║
    ║                                                       ║
    ╚═══════════════════════════════════════════════════════╝
EOF
    echo -e "${NC}\n"

    log "==================== AWX Installation Started ===================="
    print_info "Installation log: $LOG_FILE"

    # Handle uninstall mode
    if $UNINSTALL_MODE; then
        uninstall_awx
        exit 0
    fi

    # Run installation steps
    check_prerequisites
    prepare_system
    install_k3s
    deploy_awx_operator
    create_awx_instance
    wait_for_awx_deployment
    display_access_info

    print_header "Installation Complete!"
    print_success "AWX Tower is now ready to use"
    print_info "Check the access information above to get started"
    
    log "==================== AWX Installation Completed ===================="
}

################################################################################
# Execute Main Function
################################################################################

main "$@"
