---
# Ansible Galaxy Collections Requirements
# Used by ee-collections.yml example

collections:
  # Community General modules - most commonly used
  - name: community.general
  
  # POSIX system modules
  - name: ansible.posix
  
  # Network automation  
  - name: ansible.netcommon
  
  # Docker/container management
  - name: community.docker

  # Postgresql modules
  - name: community.postgresql

  # ansible.windows modules for Windows management
  - name: ansible.windows

  # AWS modules
  - name: amazon.aws

  # MYSQL modules
  - name: community.mysql

  # Vmware modules
  - name: community.vmware